In [1]:
import re
import numpy as np
import pandas as pd
import nltk


In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/tim/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [206]:
text = "production, wake topology, and propulsive performance of a pitching and rolling wing. Although our numerical values do not fully match those from the original study Li and Dong5, we obtain the same trends and thus consider this replication attempt to be successful. A CFD solver typically outputs the solution of primary variables. For example, PetIBM outputs the pressure and velocity fields, as well as the body forces. We often use multiple post-processing scripts to generate the final data and figures reported and analyzed in the manuscript; it involves computing secondary data, such as the vorticity field, the aerodynamic power and forces. If the code is not made available, readers cannot inspect what has been done to produce these data; bugs introduced in these post-processing steps would go undetected. If no code is available, we cannot explain discrepancies observed between our replication and the original study. As Donoho and coworkers14 once said: “The only way we’d ever get to the bottom of such a discrepancy is if we both worked reproducibly and studied detailed differences between code and data.” We made our best efforts to ensure that our replication study is reproducible. Our computational application makes use of fully open-source tools, and we created a GitHub repository6 for this study. The repository contains the source code of the PetIBM application, as well as all input files of the simulations reported here, and pre- and postprocessing Python scripts. We adopted a reproducible workflow to run computational simulations; it makes use of Docker images and Singularity recipes to capture the computational environment. With Singularity, we ran container-based jobs on our universitymanaged HPC cluster. The GitHub repository also contains the job-submission scripts that were use to run the simulations on our cluster; they can be adapted to run on other platforms if readers are interested in reproducing our results. Admittedly, not everyone has access to an HPC cluster with GPU nodes and with Singularity installed. Lacking those resources, it becomes difficult to fully reproduce our workflow. However, we made the effort to deposit on Zenodo7 the primary data (directly output from our CFD solver) and post-processing scripts needed to reproduce the figures of the present manuscript. Once the Zenodo repository is downloaded, readers should be able to spin up a Docker container and run a Bash script to compute the secondary data and generate the figures, or generate different figures to explore the data in new ways. The Docker images produced and used for this study are stored on DockerHub8, under a basic free subscription. In the event Docker adopts a policy to automatically purge inactive images (those who have not been recently downloaded) from the Hub, the Dockerfiles are version-controlled on the GitHub repository and can be used to rebuild the images. We spent time engineering a transparent and reproducible workflow to produce the artifacts of this replication study. Surely, we cannot assert our steps will be fully reproducible in years from now; the software stack could very well become obsolete with new hardware generations. While the likelihood of the study being reproducible may decrease with the years, the transparency of the steps we took to generate the data shall remain constant."

In [207]:
token_count = len(nltk.word_tokenize(text))
print(token_count)

590


In [5]:
nltk.sent_tokenize(text)

['production, wake topology, and propulsive performance of a pitching and rolling wing.',
 'Although our numerical values do not fully match those from the original study Li and Dong5, we obtain the same trends and thus consider this replication attempt to be successful.',
 'A CFD solver typically outputs the solution of primary variables.',
 'For example, PetIBM outputs the pressure and velocity fields, as well as the body forces.',
 'We often use multiple post-processing scripts to generate the final data and figures reported and analyzed in the manuscript; it involves computing secondary data, such as the vorticity field, the aerodynamic power and forces.',
 'If the code is not made available, readers cannot inspect what has been done to produce these data; bugs introduced in these post-processing steps would go undetected.',
 'If no code is available, we cannot explain discrepancies observed between our replication and the original study.',
 'As Donoho and coworkers14 once said: “T

Try and get working for > 1000 tokens

In [149]:
text2 = "The final product of the original study is a published manuscript in the journal Physics of Fluids. Although the manuscript is well detailed, the code and input data used to produce the computational results were not made publicly available by the authors. In that regard, we consider the study to not be reproducible. Thus, we aim to replicate the scientific findings claimed in the original study with our own research software stack and deliver reproducible results. PetIBM10 is developed in the open under the permissive (non-copyleft) 3-Clause BSD license, version-controlled with Git, and hosted on a public GitHub repository.2 Each major release of the software is archived on the data repository Zenodo. Our implementation of the three-dimensional rolling and pitching wing, which relies on PetIBM, is also open source and available on GitHub3 under the same license. The repository contains all input data and processing scripts that were used to produce the computational results reported in the next section. This allows anyone to inspect the code, to verify the steps that were taken to produce computational results, and to modify and re-use it for other applications. The repository also includes README files to guide readers that may be interested in re-running the analysis. Upon submission of the present manuscript, the application repository, as well as the data needed to reproduce the figures, have been archived on Zenodo. We leveraged our University high-performance-computing (HPC) cluster, called Pegasus, to run all simulations reported here. (We used computational nodes with Dual 20-Core 3.70GHz Intel Xeon Gold 6148 processors and NVIDIA V100 GPU devices.) To reduce the burden of building PetIBM and its applications on the cluster, we used the container technology from Docker11 and Singularity.12 Containers allow us to capture the conditions of analysis in a formatted image that can be shared with others. We have already used Docker containers in the past to create a reproducible workflow for scientific applications on the public cloud provider Microsoft Azure.13 Here, we aim to adopt a similar workflow on our local HPC cluster. Early in this replication study, we hit a snag: Docker is not available to users on Pegasus. Indeed, Docker is not available at most HPC centers for security reasons. Submitting container-based jobs with Docker implies running a Docker daemon (a background process) that requires root privileges that users do not and should not have on shared production clusters. Thus, we decided to leverage the Singularity container technology to conduct the replication study on Pegasus. Singularity is more recent than Docker, was designed from the ground up to prevent escalation of user privileges, and is compatible with Docker images. Our reproducible workflow starts with creating a Docker image that installs PetIBM and its applications, as well as all their dependencies. We then push the image to a public registry on DockerHub.4 Anyone interested in using the application code can now pull the image from the registry and spin up a Docker container to get a faithfully reproduced computational environment. Next, we use the cloud service Singularity Hub to build a"

In [152]:
text3 = text + " " + text2
print(len(nltk.word_tokenize(text3)))

1150


In [160]:
a = np.arange(0, 10)
b = np.arange(10, 20)
c = np.arange(20, 30)
d = np.arange(30, 40)

l = [a, b, c, d]

# select an index in l and get all the arrays before it
print(l[:2])

np.array([x for x in l[:2]]).ravel()

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [235]:
" ".join([str(s) for s in np.arange(0, 1700)])

'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 2

In [270]:
# text = text3 * 5

text = ". ".join([str(s) for s in np.arange(0, 16)])

# calculate the number of tokens in text
token_count = len(nltk.word_tokenize(text))


max_split_length = 5

n_splits = int(np.ceil(token_count / max_split_length))
print(n_splits)

sent = np.array(nltk.sent_tokenize(text))

# create an array of sentence token lengths
sent_token_lengths = np.array([len(nltk.word_tokenize(s)) for s in sent])

sent_split_lengths = np.array_split(sent_token_lengths, n_splits)

sent_split_indices = np.array_split(np.arange(0, len(sent_token_lengths)), n_splits)

split_dict = {}
for i in range(n_splits):
    print("i: ", i)
    chunk_len = int(np.sum(sent_split_lengths[i]))
    # print("chunk_len: ", chunk_len)
    chunk_indices = list(sent_split_indices[i])
    if i == 0:
        for j in zip(sent_split_lengths[i+1], sent_split_indices[i+1]):
            if chunk_len + j[0] <= max_split_length:
                chunk_len += j[0]
                chunk_indices = chunk_indices + [j[1]]
        
        split_text = " ".join([s for s in sent[chunk_indices]])
        split_dict[i] = [split_text, chunk_len]

    elif i > 0 and i < n_splits - 2:
        
        if i == 1:
            backward_indices = np.hstack(np.array(sent_split_indices[:i], dtype=object))
            backward_lengths = np.hstack(np.array(sent_split_lengths[:i], dtype=object))

            forwards_indices = np.hstack(np.array(sent_split_indices[i+1:], dtype=object))
            forwards_lengths = np.hstack(np.array(sent_split_lengths[i+1:], dtype=object))
            break
        # elif i == n_splits - 2:
        #     print("second to last")
        #     forwards_indices = sent_split_indices[i:]
        #     forwards_lengths = sent_split_lengths[i:]

        #     backward_indices = np.hstack(np.array(sent_split_indices[:i-1], dtype=object))
        #     backward_lengths = np.hstack(np.array(sent_split_lengths[:i-1], dtype=object))
        else:

            backward_indices = np.hstack(np.array(sent_split_indices[:i-1], dtype=object))
            backward_lengths = np.hstack(np.array(sent_split_lengths[:i-1], dtype=object))
            forwards_indices = np.hstack(np.array(sent_split_indices[i:], dtype=object))
            forwards_lengths = np.hstack(np.array(sent_split_lengths[i:], dtype=object))

        # add forward and backwards lengths/indices
        for j in zip(forwards_lengths, forwards_indices):
            # print("forwards_lengths:", j[0])
            if chunk_len + j[0] <= int((max_split_length - chunk_len) / 2.0):
                chunk_len += j[0]
                chunk_indices = chunk_indices + [j[1]]

        for j in zip(backward_indices[::-1], forwards_indices[::-1]):
            if chunk_len + j[0] <= max_split_length:
                chunk_len += j[0]
                chunk_indices = [j[1]] + chunk_indices
        split_text = " ".join([s for s in sent[chunk_indices]])
        split_dict[i] = [split_text, chunk_len]
        
    else:
        for j in zip(sent_split_lengths[i-1][::-1], sent_split_indices[i-1][::-1]):
            if chunk_len + j[0] <= max_split_length:
                chunk_len += j[0]
                chunk_indices = [j[1]] + chunk_indices
        split_text = " ".join([s for s in sent[chunk_indices]])
        split_dict[i] = [split_text, chunk_len]

7
i:  0
i:  1


In [271]:
print(backward_indices)
print(forwards_indices)
print(chunk_indices)

[0 1 2]
[6 7 8 9 10 11 12 13 14 15]
[3, 4, 5]


In [247]:
len(nltk.word_tokenize(split_dict[0][0]))

10

In [218]:
chunk_indices

[180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197]

In [186]:
backward_indices

array([array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
              17])                                                               ,
       array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
              35])                                                               ,
       array([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])],
      dtype=object)

**Working!**

In [146]:
# calculate the number of tokens in text
token_count = len(nltk.word_tokenize(text))


max_split_length = 500

n_splits = int(np.ceil(token_count / max_split_length))

sent = np.array(nltk.sent_tokenize(text))

# create an array of sentence token lengths
sent_token_lengths = np.array([len(nltk.word_tokenize(s)) for s in sent])

sent_split_lengths = np.array_split(sent_token_lengths, n_splits)

sent_split_indices = np.array_split(np.arange(0, len(sent_token_lengths)), n_splits)

split_dict = {}
for i in range(n_splits):
    chunk_len = int(np.sum(sent_split_lengths[i]))
    chunk_indices = list(sent_split_indices[i])
    if i == 0:
        for j in zip(sent_split_lengths[i+1], sent_split_indices[i+1]):
            if chunk_len + j[0] <= max_split_length:
                chunk_len += j[0]
                chunk_indices = chunk_indices + [j[1]]
        
        split_text = " ".join([s for s in sent[chunk_indices]])
        split_dict[i] = [split_text, chunk_len]

    else:
        for j in zip(sent_split_lengths[i-1][::-1], sent_split_indices[i-1][::-1]):
            if chunk_len + j[0] <= max_split_length:
                chunk_len += j[0]
                chunk_indices = [j[1]] + chunk_indices
        split_text = " ".join([s for s in sent[chunk_indices]])
        split_dict[i] = [split_text, chunk_len]

i:  0
i:  1


In [147]:
split_text = split_dict[0][0]
split_text

'production, wake topology, and propulsive performance of a pitching and rolling wing. Although our numerical values do not fully match those from the original study Li and Dong5, we obtain the same trends and thus consider this replication attempt to be successful. A CFD solver typically outputs the solution of primary variables. For example, PetIBM outputs the pressure and velocity fields, as well as the body forces. We often use multiple post-processing scripts to generate the final data and figures reported and analyzed in the manuscript; it involves computing secondary data, such as the vorticity field, the aerodynamic power and forces. If the code is not made available, readers cannot inspect what has been done to produce these data; bugs introduced in these post-processing steps would go undetected. If no code is available, we cannot explain discrepancies observed between our replication and the original study. As Donoho and coworkers14 once said: “The only way we’d ever get to 